# site settings
title: Rudmintur
subtitle: Worldwide tour agency
email: elenatourinfo@gmail.com
description: Website description "trololo"
baseurl: "/site" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Republicii
city: Cahul
state: CH
zip_code: 3901
country: Republic of Modlova
phone: (716) 555-5555

# social settings
500px_url:
facebook_url:
github_url: https://rudmintur.github.io/site/
gitlab_url: https://rudmintur.github.io/site/
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
