# site settings
title: Rudmintur
subtitle: Worldwide tour agency
email: elenatourinfo@gmail.com
description: Website description "trololo"
baseurl: "/site" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

author:
street_address: Republicii
city: Cahul
state: CH
zip_code: 3901
country: Republic of Modlova
phone: +373 299 3 23 02


#language features


# social settings
500px_url:
facebook_url: https://www.facebook.com/Rudmin-Tur-Agentie-de-Turism-1809155125993836
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
gems:
  - jemoji
