# site settings
title: Rudmintur
subtitle: туристическое агенство по всем направлениям
email: elenatourinfo@gmail.com
description: Туристическое агентство Rudmin-Tur - самостоятельная туристическая компания с семейной формой бизнесса и персональной ответственностью!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rudmintur.md" # the base hostname & protocol for your site

author:
street_address: Republicii
city: Cahul
state: CH
zip_code: 3901
country: Republic of Modlova
phone: +373 299 3 23 02
phone2: +373 798 04 044


#language features


# social settings
500px_url:
facebook_url: https://www.facebook.com/Rudmin-Tur-Agentie-de-Turism-1809155125993836
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/rudmintur/
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
gems:
  - jemoji
